/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pacote;

import Entidades.Elevador;
import java.awt.Color;


/**
 *
 * @author andre
 */
public class TelaElevador extends javax.swing.JFrame {
    Elevador elevador = new Elevador();
    public TelaElevador() {
        initComponents();
        setLocationRelativeTo(null);
        btnChamaTerrer.setBackground(new Color(0,0,0,0));
        btnChamar1andar.setBackground(new Color(0,0,0,0));
        btnChamar2andar.setBackground(new Color(0,0,0,0));
        btnChamar3andar.setBackground(new Color(0,0,0,0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ind3 = new javax.swing.JLabel();
        ind2 = new javax.swing.JLabel();
        ind1 = new javax.swing.JLabel();
        ind0 = new javax.swing.JLabel();
        btnChamar3andar = new javax.swing.JButton();
        btnChamar1andar = new javax.swing.JButton();
        btnChamar2andar = new javax.swing.JButton();
        btnChamaTerrer = new javax.swing.JButton();
        imgElevador = new javax.swing.JLabel();
        imgElevador4 = new javax.swing.JLabel();
        imgElevador2 = new javax.swing.JLabel();
        imgElevador3 = new javax.swing.JLabel();
        imgPredio = new javax.swing.JLabel();
        imgAutomato = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ind3.setForeground(new java.awt.Color(0, 255, 255));
        ind3.setText("0");
        getContentPane().add(ind3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 60, -1, -1));

        ind2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ind2.setForeground(new java.awt.Color(0, 255, 255));
        ind2.setText("0");
        getContentPane().add(ind2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 230, -1, -1));

        ind1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ind1.setForeground(new java.awt.Color(0, 255, 255));
        ind1.setText("0");
        getContentPane().add(ind1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 410, -1, -1));

        ind0.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ind0.setForeground(new java.awt.Color(0, 255, 255));
        ind0.setText("0");
        getContentPane().add(ind0, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 590, -1, -1));

        btnChamar3andar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChamar3andar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamar3andarActionPerformed(evt);
            }
        });
        getContentPane().add(btnChamar3andar, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 130, 22, 22));

        btnChamar1andar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChamar1andar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamar1andarActionPerformed(evt);
            }
        });
        getContentPane().add(btnChamar1andar, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 485, 22, 22));

        btnChamar2andar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChamar2andar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamar2andarActionPerformed(evt);
            }
        });
        getContentPane().add(btnChamar2andar, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 310, 22, 22));

        btnChamaTerrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChamaTerrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamaTerrerActionPerformed(evt);
            }
        });
        getContentPane().add(btnChamaTerrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 660, 22, 22));

        imgElevador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/ElevadorAberto.png"))); // NOI18N
        getContentPane().add(imgElevador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        imgElevador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/ElevadorFechado.png"))); // NOI18N
        getContentPane().add(imgElevador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        imgElevador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/ElevadorFechado.png"))); // NOI18N
        getContentPane().add(imgElevador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        imgElevador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/ElevadorFechado.png"))); // NOI18N
        getContentPane().add(imgElevador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        imgPredio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/imgPredio.png"))); // NOI18N
        getContentPane().add(imgPredio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgAutomato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/AutomatoA02.png"))); // NOI18N
        getContentPane().add(imgAutomato, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/FundoBranco.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 0, 450, 250));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/FundoBranco.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 530, 450, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChamar3andarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamar3andarActionPerformed
        imgPredio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/imgPredio3.png")));
        btnChamaTerrer.setVisible(false);
        btnChamar1andar.setVisible(false);
        btnChamar2andar.setVisible(false);
        btnChamar3andar.setVisible(false);
        int andar = elevador.getAndares();
        int andarDest = 3;
        
        switch (andar){
            case 0 :{
               elevador.subirAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador,imgElevador4);   
               break;
            }
            case 1 :{
              elevador.subirAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador2,imgElevador4);              
              break;
            }
            case 2: {
              elevador.subirAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador3,imgElevador4);
              break;
            }
            case 3: {
              System.out.println("Elevador já está nesse andar");
              btnChamaTerrer.setVisible(true);
              btnChamar1andar.setVisible(true);
              btnChamar2andar.setVisible(true);
              btnChamar3andar.setVisible(true);
              break;
            }  
        }
        
        
        
    }//GEN-LAST:event_btnChamar3andarActionPerformed

    private void btnChamaTerrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamaTerrerActionPerformed
        imgPredio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/imgPredioT.png")));
        btnChamaTerrer.setVisible(false);
        btnChamar1andar.setVisible(false);
        btnChamar2andar.setVisible(false);
        btnChamar3andar.setVisible(false);
        int andar = elevador.getAndares();
        int andarDest = 0;

        switch (andar){
            case 0 :{
               System.out.println("Elevador já está nesse andar");
               btnChamaTerrer.setVisible(true);
              btnChamar1andar.setVisible(true);
              btnChamar2andar.setVisible(true);
              btnChamar3andar.setVisible(true);
               break;
            }
            case 1 :{
              elevador.descerAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador2,imgElevador);              
              break;
            }
            case 2: {
              elevador.descerAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador3,imgElevador);
              break;
            }
            case 3: {
              elevador.descerAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador4,imgElevador);
              break;
            }  
        }
        
    }//GEN-LAST:event_btnChamaTerrerActionPerformed

    private void btnChamar2andarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamar2andarActionPerformed
        imgPredio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/imgPredio2.png")));
        btnChamaTerrer.setVisible(false);
        btnChamar1andar.setVisible(false);
        btnChamar2andar.setVisible(false);
        btnChamar3andar.setVisible(false);
        int andar = elevador.getAndares();
        int andarDest = 2;
        switch (andar){
            case 0 :{
               elevador.subirAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador,imgElevador3); 
               break;
            }
            case 1 :{
              elevador.subirAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador2,imgElevador3);              
              break;
            }
            case 2: {
              System.out.println("Elevador já está nesse andar");  
              btnChamaTerrer.setVisible(true);
              btnChamar1andar.setVisible(true);
              btnChamar2andar.setVisible(true);
              btnChamar3andar.setVisible(true);
              break;
            }
            case 3: {
              elevador.descerAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador4,imgElevador3);
              break;
            }  
        }
    }//GEN-LAST:event_btnChamar2andarActionPerformed

    private void btnChamar1andarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamar1andarActionPerformed
        imgPredio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens2/imgPredio1.png")));
        btnChamaTerrer.setVisible(false);
        btnChamar1andar.setVisible(false);
        btnChamar2andar.setVisible(false);
        btnChamar3andar.setVisible(false);
        int andar = elevador.getAndares();
        int andarDest = 1;
        switch (andar){
            case 0 :{
               elevador.subirAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador,imgElevador2); 
               break;
            }
            case 1 :{
              System.out.println("Elevador já está nesse andar");  
              btnChamaTerrer.setVisible(true);
              btnChamar1andar.setVisible(true);
              btnChamar2andar.setVisible(true);
              btnChamar3andar.setVisible(true);
              break;
            }
            case 2: {
              elevador.descerAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador3,imgElevador2);
              break;  
            }
            case 3: {
              elevador.descerAndares(ind0,ind1,ind2, ind3,imgPredio,btnChamaTerrer, btnChamar1andar, btnChamar2andar, btnChamar3andar,andar,andarDest, imgAutomato,imgElevador4,imgElevador2);
              break;
            }  
        }
    }//GEN-LAST:event_btnChamar1andarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaElevador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaElevador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamaTerrer;
    private javax.swing.JButton btnChamar1andar;
    private javax.swing.JButton btnChamar2andar;
    private javax.swing.JButton btnChamar3andar;
    private javax.swing.JLabel imgAutomato;
    private javax.swing.JLabel imgElevador;
    private javax.swing.JLabel imgElevador2;
    private javax.swing.JLabel imgElevador3;
    private javax.swing.JLabel imgElevador4;
    private javax.swing.JLabel imgPredio;
    private javax.swing.JLabel ind0;
    private javax.swing.JLabel ind1;
    private javax.swing.JLabel ind2;
    private javax.swing.JLabel ind3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
