/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pacote;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre
 */
public class TelaPrincipal extends javax.swing.JFrame {

   int contCookie = 0;
   int contChocolate = 0;
   int contGummy = 0;
    public TelaPrincipal() {
        super("CandyShop");
        initComponents();
        setLocationRelativeTo(null);
        btnGummy.setBackground(new Color(0,0,0,0));
        btnChocolate.setBackground(new Color(0,0,0,0));
        btnCookie.setBackground(new Color(0,0,0,0));
        btn1real.setBackground(new Color(0,0,0,0));
        btn2reais.setBackground(new Color(0,0,0,0));
        btn5reais.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Saldo = new javax.swing.JLabel();
        imgChoco1 = new javax.swing.JLabel();
        imgChoco3 = new javax.swing.JLabel();
        btn1real = new javax.swing.JButton();
        imgChoco4 = new javax.swing.JLabel();
        imgChoco5 = new javax.swing.JLabel();
        imgChoco6 = new javax.swing.JLabel();
        btn2reais = new javax.swing.JButton();
        imgGummy1 = new javax.swing.JLabel();
        btn5reais = new javax.swing.JButton();
        imgCookie1 = new javax.swing.JLabel();
        imgCookie2 = new javax.swing.JLabel();
        imgGummy2 = new javax.swing.JLabel();
        imgChoco2 = new javax.swing.JLabel();
        imgGummy3 = new javax.swing.JLabel();
        btnGummy = new javax.swing.JButton();
        btnChocolate = new javax.swing.JButton();
        btnCookie = new javax.swing.JButton();
        imgMaquina = new javax.swing.JLabel();
        imgManual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Saldo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Saldo.setText("R$ 0,00");
        getContentPane().add(Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 197, 90, 30));

        imgChoco1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223730552138633227/choco2.png?ex=661aeae3&is=660875e3&hm=1adca460507d195e71c434fcced64dde52ced01822ae0b89849be42dc8ade907&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        imgChoco3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223730552373510266/choco1.png?ex=661aeae3&is=660875e3&hm=ebb6e6a238f2aded6b27d1aa84813309aa17e443f9b9c61d616610e5a3c79061&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, -1, -1));

        btn1real.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn1real, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 120, 110));

        imgChoco4.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223730552138633227/choco2.png?ex=661aeae3&is=660875e3&hm=1adca460507d195e71c434fcced64dde52ced01822ae0b89849be42dc8ade907&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, -1));

        imgChoco5.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223730552373510266/choco1.png?ex=661aeae3&is=660875e3&hm=ebb6e6a238f2aded6b27d1aa84813309aa17e443f9b9c61d616610e5a3c79061&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, -1));

        imgChoco6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223730552138633227/choco2.png?ex=661aeae3&is=660875e3&hm=1adca460507d195e71c434fcced64dde52ced01822ae0b89849be42dc8ade907&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, -1, -1));

        btn2reais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn2reais, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 240, 110));

        imgGummy1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223729855003103302/imgGummy.png?ex=661aea3d&is=6608753d&hm=ec11734df35e884a903f2ae1d1ed0f3d18323fd8f9b921aa0d2ba1dc6458b216&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgGummy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, -1, -1));

        btn5reais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn5reais, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 230, 110));

        imgCookie1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223731146899062974/cookie2.png?ex=661aeb71&is=66087671&hm=4d86db621f002af1f8ffe52318692e40461922d9dd8945b1abd475c7d71e90ea&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgCookie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 524, -1, -1));

        imgCookie2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223731146475573268/cookie1.png?ex=661aeb71&is=66087671&hm=011c697ded0cb0033cf4b2acc9404e129d39d29431ed3f08188993fe0a45f751&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgCookie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 514, -1, -1));

        imgGummy2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223729855003103302/imgGummy.png?ex=661aea3d&is=6608753d&hm=ec11734df35e884a903f2ae1d1ed0f3d18323fd8f9b921aa0d2ba1dc6458b216&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgGummy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        imgChoco2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223730552373510266/choco1.png?ex=661aeae3&is=660875e3&hm=ebb6e6a238f2aded6b27d1aa84813309aa17e443f9b9c61d616610e5a3c79061&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        imgGummy3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223729855003103302/imgGummy.png?ex=661aea3d&is=6608753d&hm=ec11734df35e884a903f2ae1d1ed0f3d18323fd8f9b921aa0d2ba1dc6458b216&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgGummy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        btnGummy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGummy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGummyMouseEntered(evt);
            }
        });
        btnGummy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGummyActionPerformed(evt);
            }
        });
        getContentPane().add(btnGummy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 287, 130, 30));

        btnChocolate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });
        getContentPane().add(btnChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 326, 130, 30));

        btnCookie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookieActionPerformed(evt);
            }
        });
        getContentPane().add(btnCookie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 365, 130, 30));

        imgMaquina.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223721693042839562/MaquinaFechadaC.png?ex=661ae2a3&is=66086da3&hm=9bdadadc9b131f197ee1bf0da2eb5ec4f9710de266282b52fd2cb6388b121767&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        imgManual.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223743128549195896/ManualMaquina.png?ex=661af699&is=66088199&hm=a350507c7cf00fa930af70b87ef252805de559815a835354f06587bc59ee4e83&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGummyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGummyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGummyMouseEntered

    private void btnGummyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGummyActionPerformed
        imgMaquina.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223721692770074686/MaquinaAbertaC.png?ex=661ae2a3&is=66086da3&hm=5bd358bb1fe968eac15151538c7ba6e700282d62e5783a82b83fa707b6bf1017&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        contGummy ++;
        if(contGummy == 0){
            imgGummy1.setVisible(true);
            imgGummy2.setVisible(true);
        }
        else if(contGummy == 1){
            imgGummy1.setVisible(false);
        }
        else if(contGummy == 2){
            imgGummy2.setVisible(false);
        }
        else if(contGummy == 3){
            imgGummy3.setVisible(false);
        }
        else{
           Font fonte = new Font("Arial", Font.PLAIN, 20);

           Saldo.setFont(fonte);
           Saldo.setText("Esgotado");
           
        }
   
    }//GEN-LAST:event_btnGummyActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        imgMaquina.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223721692770074686/MaquinaAbertaC.png?ex=661ae2a3&is=66086da3&hm=5bd358bb1fe968eac15151538c7ba6e700282d62e5783a82b83fa707b6bf1017&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        contChocolate ++;
        if(contChocolate == 0){
            imgChoco2.setVisible(true);
            imgChoco1.setVisible(true);
        }
        else if(contChocolate == 3){
            imgChoco2.setVisible(false);
        }
        else if(contChocolate == 4){
            imgChoco1.setVisible(false);
        }
        else if(contChocolate == 2){
            imgChoco3.setVisible(false);
        }
        else if(contChocolate == 1){
            imgChoco4.setVisible(false);
        }
        else if(contChocolate == 6){
            imgChoco5.setVisible(false);
        }
        else if(contChocolate == 5){
            imgChoco6.setVisible(false);
        }
        else{
           Font fonte = new Font("Arial", Font.PLAIN, 20);

           Saldo.setFont(fonte);
           Saldo.setText("Esgotado");
           
        }
        
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnCookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookieActionPerformed
        imgMaquina.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1223721692770074686/MaquinaAbertaC.png?ex=661ae2a3&is=66086da3&hm=5bd358bb1fe968eac15151538c7ba6e700282d62e5783a82b83fa707b6bf1017&")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        contCookie ++;
        if(contCookie == 0){
            imgCookie2.setVisible(true);
            imgCookie1.setVisible(true);
        }
        else if(contCookie == 1){
            imgCookie2.setVisible(false);
        }
        else if(contCookie == 2){
            imgCookie1.setVisible(false);
        }
        else{
           Font fonte = new Font("Arial", Font.PLAIN, 20);

           Saldo.setFont(fonte);
           Saldo.setText("Esgotado");
           
        }
        
       
    }//GEN-LAST:event_btnCookieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Saldo;
    private javax.swing.JButton btn1real;
    private javax.swing.JButton btn2reais;
    private javax.swing.JButton btn5reais;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnCookie;
    private javax.swing.JButton btnGummy;
    private javax.swing.JLabel imgChoco1;
    private javax.swing.JLabel imgChoco2;
    private javax.swing.JLabel imgChoco3;
    private javax.swing.JLabel imgChoco4;
    private javax.swing.JLabel imgChoco5;
    private javax.swing.JLabel imgChoco6;
    private javax.swing.JLabel imgCookie1;
    private javax.swing.JLabel imgCookie2;
    private javax.swing.JLabel imgGummy1;
    private javax.swing.JLabel imgGummy2;
    private javax.swing.JLabel imgGummy3;
    private javax.swing.JLabel imgManual;
    private javax.swing.JLabel imgMaquina;
    // End of variables declaration//GEN-END:variables
}
