/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pacote;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre
 */
public class TelaPrincipal extends javax.swing.JFrame {

   int contCookie = 0;
   int contChocolate = 0;
   int contGummy = 0;
    public TelaPrincipal() {
        super("CandyShop");
        initComponents();
        setLocationRelativeTo(null);
        btnGummy.setBackground(new Color(0,0,0,0));
        btnChocolate.setBackground(new Color(0,0,0,0));
        btnCookie.setBackground(new Color(0,0,0,0));
        btn1real.setBackground(new Color(0,0,0,0));
        btn2reais.setBackground(new Color(0,0,0,0));
        btn5reais.setBackground(new Color(0,0,0,0));
        btnPegar.setBackground(new Color(0,0,0,0));
        OutGummy1.setVisible(false);
        OutChoco1.setVisible(false);
        OutChoco2.setVisible(false);
        OutCookie1.setVisible(false);
        OutCookie2.setVisible(false);
        btnPegar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Saldo = new javax.swing.JLabel();
        OutGummy1 = new javax.swing.JLabel();
        OutCookie2 = new javax.swing.JLabel();
        OutChoco1 = new javax.swing.JLabel();
        btnPegar = new javax.swing.JButton();
        OutChoco2 = new javax.swing.JLabel();
        OutCookie1 = new javax.swing.JLabel();
        imgChoco1 = new javax.swing.JLabel();
        imgChoco3 = new javax.swing.JLabel();
        btn1real = new javax.swing.JButton();
        imgChoco4 = new javax.swing.JLabel();
        imgChoco5 = new javax.swing.JLabel();
        imgChoco6 = new javax.swing.JLabel();
        btn2reais = new javax.swing.JButton();
        imgGummy1 = new javax.swing.JLabel();
        btn5reais = new javax.swing.JButton();
        imgCookie1 = new javax.swing.JLabel();
        imgCookie2 = new javax.swing.JLabel();
        imgGummy2 = new javax.swing.JLabel();
        imgChoco2 = new javax.swing.JLabel();
        imgGummy3 = new javax.swing.JLabel();
        btnGummy = new javax.swing.JButton();
        btnChocolate = new javax.swing.JButton();
        btnCookie = new javax.swing.JButton();
        imgMaquina = new javax.swing.JLabel();
        imgManual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Saldo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Saldo.setText("R$ 0,00");
        getContentPane().add(Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 197, 90, 30));

        OutGummy1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/OutGummy.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(OutGummy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 653, -1, -1));

        OutCookie2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/Outcookie2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(OutCookie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 653, -1, -1));

        OutChoco1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/Outchoco1.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(OutChoco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 653, -1, -1));

        btnPegar.setText("Pegar");
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 120, 80));

        OutChoco2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/Outchoco2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(OutChoco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 653, -1, -1));

        OutCookie1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/Outcookie1.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(OutCookie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 653, -1, -1));

        imgChoco1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/choco2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        imgChoco3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/choco1.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, -1, -1));

        btn1real.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn1real, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 120, 110));

        imgChoco4.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/choco2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, -1));

        imgChoco5.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/choco1.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, -1));

        imgChoco6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/choco2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, -1, -1));

        btn2reais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn2reais, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 240, 110));

        imgGummy1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/imgGummy.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgGummy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, -1, -1));

        btn5reais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn5reais, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 230, 110));

        imgCookie1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/cookie2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgCookie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 524, -1, -1));

        imgCookie2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/cookie1.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgCookie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 514, -1, -1));

        imgGummy2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/imgGummy.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgGummy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        imgChoco2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/choco1.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgChoco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        imgGummy3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/imgGummy.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgGummy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        btnGummy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGummy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGummyMouseEntered(evt);
            }
        });
        btnGummy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGummyActionPerformed(evt);
            }
        });
        getContentPane().add(btnGummy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 287, 130, 30));

        btnChocolate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });
        getContentPane().add(btnChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 326, 130, 30));

        btnCookie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookieActionPerformed(evt);
            }
        });
        getContentPane().add(btnCookie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 365, 130, 30));

        imgMaquina.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/MaquinaFechadaC.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        imgManual.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/ManualMaquina.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGummyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGummyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGummyMouseEntered

    private void btnGummyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGummyActionPerformed
        
        contGummy ++;
        if(contGummy <4){
            imgMaquina.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/MaquinaAbertaC.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        }
        if(contGummy == 0){
            imgGummy1.setVisible(true);
            imgGummy2.setVisible(true);
            OutGummy1.setVisible(true);
        }
        else if(contGummy == 1){
            imgGummy1.setVisible(false);
            OutGummy1.setVisible(true);
        }
        else if(contGummy == 2){
            imgGummy2.setVisible(false);
            OutGummy1.setVisible(true);
        }
        else if(contGummy == 3){
            imgGummy3.setVisible(false);
            OutGummy1.setVisible(true);
        }
        else{
           Font fonte = new Font("Arial", Font.PLAIN, 20);

           Saldo.setFont(fonte);
           Saldo.setText("Esgotado");
           
        }
        btnGummy.setVisible(false);
        btnChocolate.setVisible(false);
        btnCookie.setVisible(false);
        btn1real.setVisible(false);
        btn2reais.setVisible(false);
        btn5reais.setVisible(false);
        btnPegar.setVisible(true);
   
    }//GEN-LAST:event_btnGummyActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        contChocolate ++;
        if(contChocolate <7){
            imgMaquina.setIcon(new javax.swing.JLabel() {
                public javax.swing.Icon getIcon() {
                    try {
                        return new javax.swing.ImageIcon(
                            new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/MaquinaAbertaC.png?raw=true")
                        );
                    } catch (java.net.MalformedURLException e) {
                    }
                    return null;
                }
            }.getIcon());
        }
 
        if(contChocolate == 0){
            imgChoco2.setVisible(true);
            imgChoco1.setVisible(true);
        }
        else if(contChocolate == 3){
            imgChoco2.setVisible(false);
            OutChoco1.setVisible(true);
        }
        else if(contChocolate == 4){
            imgChoco1.setVisible(false);
            OutChoco2.setVisible(true);
        }
        else if(contChocolate == 2){
            imgChoco3.setVisible(false);
            OutChoco1.setVisible(true);
        }
        else if(contChocolate == 1){
            imgChoco4.setVisible(false);
            OutChoco2.setVisible(true);
        }
        else if(contChocolate == 6){
            imgChoco5.setVisible(false);
            OutChoco1.setVisible(true);
        }
        else if(contChocolate == 5){
            imgChoco6.setVisible(false);
            OutChoco2.setVisible(true);
        }
        else{
           Font fonte = new Font("Arial", Font.PLAIN, 20);

           Saldo.setFont(fonte);
           Saldo.setText("Esgotado");
           
        }
        btnGummy.setVisible(false);
        btnChocolate.setVisible(false);
        btnCookie.setVisible(false);
        btn1real.setVisible(false);
        btn2reais.setVisible(false);
        btn5reais.setVisible(false);
        btnPegar.setVisible(true);
        
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnCookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookieActionPerformed
        contCookie ++;
        if(contCookie <3){
            imgMaquina.setIcon(new javax.swing.JLabel() {
                public javax.swing.Icon getIcon() {
                    try {
                        return new javax.swing.ImageIcon(
                            new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/MaquinaAbertaC.png?raw=true")
                        );
                    } catch (java.net.MalformedURLException e) {
                    }
                    return null;
                }
            }.getIcon());
        }
        if(contCookie == 0){
            imgCookie2.setVisible(true);
            imgCookie1.setVisible(true);
        }
        else if(contCookie == 1){
            imgCookie2.setVisible(false);
            OutCookie1.setVisible(true);
        }
        else if(contCookie == 2){
            imgCookie1.setVisible(false);
            OutCookie2.setVisible(true);
        }
        else{
           Font fonte = new Font("Arial", Font.PLAIN, 20);

           Saldo.setFont(fonte);
           Saldo.setText("Esgotado");
           
        }
        btnGummy.setVisible(false);
        btnChocolate.setVisible(false);
        btnCookie.setVisible(false);
        btn1real.setVisible(false);
        btn2reais.setVisible(false);
        btn5reais.setVisible(false);
        btnPegar.setVisible(true);
        
       
    }//GEN-LAST:event_btnCookieActionPerformed

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
        OutGummy1.setVisible(false);
        OutChoco1.setVisible(false);
        OutChoco2.setVisible(false);
        OutCookie1.setVisible(false);
        OutCookie2.setVisible(false);
        imgMaquina.setIcon(new javax.swing.JLabel() {
                public javax.swing.Icon getIcon() {
                    try {
                        return new javax.swing.ImageIcon(
                            new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/Teoria-da-Computacao-e-Compiladores/blob/main/ProjetoA3/MaquinaDeDoce/src/main/java/Imagens/MaquinaFechadaC.png?raw=true")
                        );
                    } catch (java.net.MalformedURLException e) {
                    }
                    return null;
                }
            }.getIcon());
        btnGummy.setVisible(true);
        btnChocolate.setVisible(true);
        btnCookie.setVisible(true);
        btn1real.setVisible(true);
        btn2reais.setVisible(true);
        btn5reais.setVisible(true);
        btnPegar.setVisible(false);
    }//GEN-LAST:event_btnPegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OutChoco1;
    private javax.swing.JLabel OutChoco2;
    private javax.swing.JLabel OutCookie1;
    private javax.swing.JLabel OutCookie2;
    private javax.swing.JLabel OutGummy1;
    private javax.swing.JLabel Saldo;
    private javax.swing.JButton btn1real;
    private javax.swing.JButton btn2reais;
    private javax.swing.JButton btn5reais;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnCookie;
    private javax.swing.JButton btnGummy;
    private javax.swing.JButton btnPegar;
    private javax.swing.JLabel imgChoco1;
    private javax.swing.JLabel imgChoco2;
    private javax.swing.JLabel imgChoco3;
    private javax.swing.JLabel imgChoco4;
    private javax.swing.JLabel imgChoco5;
    private javax.swing.JLabel imgChoco6;
    private javax.swing.JLabel imgCookie1;
    private javax.swing.JLabel imgCookie2;
    private javax.swing.JLabel imgGummy1;
    private javax.swing.JLabel imgGummy2;
    private javax.swing.JLabel imgGummy3;
    private javax.swing.JLabel imgManual;
    private javax.swing.JLabel imgMaquina;
    // End of variables declaration//GEN-END:variables
}
