/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pacote;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author andre
 */
public class TelaCompra extends javax.swing.JFrame {

    /**
     * Creates new form TelaCompra
     */
    public TelaCompra() {
        initComponents();
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose(); // Fecha a janela
            }
        });
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    public TelaCompra(int saldoFinal, int tipoDoce) {
        initComponents();
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose(); // Fecha a janela
            }
        });
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        img1real.setVisible(false);
        img2reais.setVisible(false);
        img2reais2.setVisible(false);
        imgChoco1.setVisible(false);
        imgChoco3.setVisible(false);
        imgGummy2.setVisible(false);
        imgCookie2.setVisible(false);
        imgCookie1.setVisible(false);
        
        if(saldoFinal==1){
            img1real.setVisible(true);
        }
        else if(saldoFinal==2){
            img2reais.setVisible(true);
        }
        else if(saldoFinal==3){
            img2reais2.setVisible(true);
            img1real.setVisible(true);
        }
        else if(saldoFinal==4){
            img2reais2.setVisible(true);
            img2reais.setVisible(true);
        }
        if(tipoDoce==1){
            imgGummy2.setVisible(true);
        }
        else if(tipoDoce==2){
            imgChoco1.setVisible(true);
        }
        else if(tipoDoce==3){
            imgChoco3.setVisible(true);
        }
        else if(tipoDoce==4){
            imgCookie2.setVisible(true);
        }
        else if(tipoDoce==5){
            imgCookie1.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgChoco1 = new javax.swing.JLabel();
        imgChoco3 = new javax.swing.JLabel();
        imgCookie2 = new javax.swing.JLabel();
        imgCookie1 = new javax.swing.JLabel();
        img1real = new javax.swing.JLabel();
        img2reais = new javax.swing.JLabel();
        img2reais2 = new javax.swing.JLabel();
        imgGummy2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgChoco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/choco2troco.png"))); // NOI18N
        getContentPane().add(imgChoco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 280, 270));

        imgChoco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/choco1troco.png"))); // NOI18N
        getContentPane().add(imgChoco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        imgCookie2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cookie1Troco.png"))); // NOI18N
        getContentPane().add(imgCookie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        imgCookie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cookie2Toco.png"))); // NOI18N
        getContentPane().add(imgCookie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, -1));

        img1real.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1real.png"))); // NOI18N
        getContentPane().add(img1real, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        img2reais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2reais.png"))); // NOI18N
        getContentPane().add(img2reais, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        img2reais2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2reais.png"))); // NOI18N
        getContentPane().add(img2reais2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        imgGummy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GummyTroco.png"))); // NOI18N
        getContentPane().add(imgGummy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 240, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imgFundoTroco.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img1real;
    private javax.swing.JLabel img2reais;
    private javax.swing.JLabel img2reais2;
    private javax.swing.JLabel imgChoco1;
    private javax.swing.JLabel imgChoco3;
    private javax.swing.JLabel imgCookie1;
    private javax.swing.JLabel imgCookie2;
    private javax.swing.JLabel imgGummy2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
